<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <OutputPath>..\..\output</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.1" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="NLog.Extensions.Hosting" Version="6.1.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers.Http\Eu.EDelivery.AS4.Receivers.Http.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers\Eu.EDelivery.AS4.Receivers.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4.Steps\Eu.EDelivery.AS4.Steps.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4.Transformers\Eu.EDelivery.AS4.Transformers.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4\Eu.EDelivery.AS4.csproj" />
  </ItemGroup>

</Project>