<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers.Http\Eu.EDelivery.AS4.Receivers.Http.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers\Eu.EDelivery.AS4.Receivers.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.Steps\Eu.EDelivery.AS4.Steps.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.Transformers\Eu.EDelivery.AS4.Transformers.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4\Eu.EDelivery.AS4.csproj" />
    </ItemGroup>
</Project>
