// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 

using System.Xml;
using System.Xml.Serialization;

namespace Eu.EDelivery.AS4.Xml;

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Messaging
{
    public Messaging()
    {
        this.mustUnderstand1 = false;
    }

    [XmlElement("SignalMessage")]
    public SignalMessage[]? SignalMessage { get; set; }

    [XmlElement("UserMessage")]
    public UserMessage[]? UserMessage { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? id { get; set; }

    [XmlAttribute(AttributeName = "Id", Namespace = Constants.Namespaces.WssSecurityUtility)]
    public string? SecurityId { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
    public bool mustUnderstand { get; set; }

    [XmlIgnore()]
    public bool mustUnderstandSpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://schemas.xmlsoap.org/soap/envelope/", DataType = "anyURI")]
    public string[]? encodingStyle { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://schemas.xmlsoap.org/soap/envelope/", DataType = "anyURI")]
    public string? actor { get; set; }

    [XmlAttribute("mustUnderstand", Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope")]
    [System.ComponentModel.DefaultValue(false)]
    public bool mustUnderstand1 { get; set; }

    [XmlIgnore()]
    public bool mustUnderstand1Specified { get; set; }

    [XmlAttribute("encodingStyle", Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope", DataType = "anyURI")]
    public string? encodingStyle1 { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope")]
    public bool relay { get; set; }

    [XmlIgnore()]
    public bool relaySpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope", DataType = "anyURI")]
    public string? role { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
public partial class SignalMessage
{

    public required MessageInfo MessageInfo { get; set; }

    public PullRequest? PullRequest { get; set; }

    public Receipt? Receipt { get; set; }

    [XmlElement("Error")]
    public Error[]? Error { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
public partial class MessageInfo
{
    [XmlElement("Timestamp")]
    public string XmlTimestamp
    {
        get => XmlConvert.ToString(Timestamp, XmlDateTimeSerializationMode.RoundtripKind);
        set
        {
            var values = value.Split('+');
            if (values.Length > 1)
            {
                value = values[0] + "Z";
            }
            Timestamp = XmlConvert.ToDateTime(value, XmlDateTimeSerializationMode.RoundtripKind);
        }
    }

    [XmlIgnore]
    public required DateTime Timestamp { get; set; }

    public required string MessageId { get; set; }

    public string? RefToMessageId { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Schema
{

    [XmlAttribute(DataType = "anyURI")]
    public required string location { get; set; }

    [XmlAttribute()]
    public string? version { get; set; }

    [XmlAttribute()]
    public string? @namespace { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class PartInfo
{

    [XmlElement("Schema")]
    public Schema[]? Schemas { get; set; }

    public Description? Description { get; set; }

    [XmlArrayItem(IsNullable = false)]
    public Property[]? PartProperties { get; set; }

    [XmlAttribute(DataType = "token")]
    public string? href { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Description
{

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public required string lang { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Property
{

    [XmlAttribute()]
    public required string name { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Service
{

    [XmlAttribute()]
    public string? type { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class AgreementRef
{

    [XmlAttribute()]
    public string? type { get; set; }

    [XmlAttribute()]
    public string? pmode { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
public partial class To
{

    [XmlElement("PartyId")]
    public required PartyId[] PartyId { get; set; }

    public required string Role { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class PartyId
{

    [XmlAttribute()]
    public required string type { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
public partial class From
{

    [XmlElement("PartyId")]
    public required PartyId[] PartyId { get; set; }

    public required string Role { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class UserMessage
{

    public required MessageInfo MessageInfo { get; set; }

    public required PartyInfo PartyInfo { get; set; }

    public required CollaborationInfo CollaborationInfo { get; set; }

    [XmlArrayItem(IsNullable = false)]
    public Property[]? MessageProperties { get; set; }

    [XmlArrayItem(IsNullable = false)]
    public PartInfo[]? PayloadInfo { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? mpc { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
public partial class PartyInfo
{

    public required From From { get; set; }

    public required To To { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
public partial class CollaborationInfo
{

    public AgreementRef? AgreementRef { get; set; }

    public required Service Service { get; set; }

    [XmlElement(DataType = "token")]
    public required string Action { get; set; }

    [XmlElement(DataType = "token")]
    public required string ConversationId { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Error
{

    public Description? Description { get; set; }

    [XmlElement(DataType = "token")]
    public string? ErrorDetail { get; set; }

    [XmlAttribute(DataType = "token")]
    public string? category { get; set; }

    [XmlAttribute(DataType = "token")]
    public string? refToMessageInError { get; set; }

    [XmlAttribute(DataType = "token")]
    public required string errorCode { get; set; }

    [XmlAttribute(DataType = "token")]
    public string? origin { get; set; }

    [XmlAttribute(DataType = "token")]
    public required string severity { get; set; }

    [XmlAttribute(DataType = "token")]
    public string? shortDescription { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
public partial class Receipt
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class PullRequest
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? mpc { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
public partial class PayloadInfo
{

    [XmlElement("PartInfo")]
    public required PartInfo[] PartInfo { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/", IsNullable = false)]
public partial class MessageProperties
{

    [XmlElement("Property")]
    public required Property[] Property { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-msg/ns/ebms/v3.0/multihop/200902/")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-msg/ns/ebms/v3.0/multihop/200902/", IsNullable = false)]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class RoutingInput
{

    public RoutingInput()
    {
        IsReferenceParameter = true;
        mustUnderstand = false;
        role = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/part2/200811/nextmsh";
    }

    public required RoutingInputUserMessage UserMessage { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? id { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2005/08/addressing")]
    public bool IsReferenceParameter { get; set; }

    [XmlIgnore()]
    public bool IsReferenceParameterSpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope")]
    [System.ComponentModel.DefaultValue(false)]
    public bool mustUnderstand { get; set; }

    [XmlIgnore()]
    public bool mustUnderstandSpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope", DataType = "anyURI")]
    public string? encodingStyle { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope")]
    public bool relay { get; set; }

    [XmlIgnore()]
    public bool relaySpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/2003/05/soap-envelope", DataType = "anyURI")]
    public string role { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-msg/ns/ebms/v3.0/multihop/200902/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class RoutingInputUserMessage
{

    [XmlElement(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public MessageInfo? MessageInfo { get; set; }

    [XmlElement(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public required PartyInfo PartyInfo { get; set; }

    [XmlElement(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    public required CollaborationInfo CollaborationInfo { get; set; }

    [XmlArray(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    [XmlArrayItem(IsNullable = false)]
    public Property[]? MessageProperties { get; set; }

    [XmlArray(Namespace = "http://docs.oasis-open.org/ebxml-msg/ebms/v3.0/ns/core/200704/")]
    [XmlArrayItem(IsNullable = false)]
    public PartInfo[]? PayloadInfo { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? mpc { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0", IsNullable = false)]
public partial class Exception : SignalIdentificationInformation
{

    public required ExceptionExceptionType ExceptionType { get; set; }

    public required string Reason { get; set; }

    public string? ExceptionMessage { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement? Any { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
public partial class ExceptionExceptionType
{

    [XmlElement("AcceptanceException", typeof(ExceptionExceptionTypeAcceptanceException))]
    [XmlElement("GeneralException", typeof(string))]
    [XmlElement("ReceiptException", typeof(ExceptionExceptionTypeReceiptException))]
    public required object Item { get; set; }
}

[Serializable()]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
public enum ExceptionExceptionTypeAcceptanceException
{

    Business,

    Performance,
}

[Serializable()]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
public enum ExceptionExceptionTypeReceiptException
{

    Syntax,

    Authorization,

    Signature,

    Sequence,
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
public partial class SignalIdentificationInformation
{

    public required string OriginalMessageIdentifier { get; set; }

    public string? OriginalDocumentIdentifier { get; set; }

    public required DateTime OriginalMessageDateTime { get; set; }

    public required DateTime ThisMessageDateTime { get; set; }

    public PartyInfoType? FromPartyInfo { get; set; }

    public PartyInfoType? ToPartyInfo { get; set; }

    public RoleType? FromRole { get; set; }

    public RoleType? ToRole { get; set; }

    public ProcessSpecificationInfoType? ProcessSpecificationInfo { get; set; }

    public string? CollaborationIdentifier { get; set; }

    public string? BusinessActivityIdentifier { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class PartyInfoType
{

    [XmlAttribute()]
    public string? type { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class RoleType
{

    public RoleType()
    {
        type = RoleTypeType.simple;
    }

    [XmlAttribute()]
    public required string name { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public RoleTypeType type { get; set; }

    [XmlIgnore()]
    public bool typeSpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
    public required string href { get; set; }
}

[Serializable()]
[XmlType(AnonymousType = true, Namespace = "http://www.w3.org/1999/xlink")]
public enum RoleTypeType
{

    simple,

    extended,

    locator,

    arc,

    resource,

    title,

    none,
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class ProcessSpecificationInfoType
{

    public ProcessSpecificationInfoType()
    {
        type = RoleTypeType.simple;
    }

    [XmlAttribute()]
    public string? instanceVersion { get; set; }

    [XmlAttribute()]
    public string? name { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink")]
    public RoleTypeType type { get; set; }

    [XmlIgnore()]
    public bool typeSpecified { get; set; }

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/1999/xlink", DataType = "anyURI")]
    public required string href { get; set; }

    [XmlAttribute()]
    public required string uuid { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0", IsNullable = false)]
public partial class ReceiptAcknowledgement : SignalIdentificationInformation
{

    [XmlArrayItem("MessagePartNRInformation", IsNullable = false)]
    public MessagePartNRInformation[]? NonRepudiationInformation { get; set; }

    [XmlElement(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType? Signature { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0", IsNullable = false)]
public partial class MessagePartNRInformation
{

    [XmlElement("MessagePartIdentifier", typeof(string))]
    [XmlElement("Reference", typeof(ReferenceType), Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public required object Item { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Reference", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class ReferenceType
{

    [XmlArrayItem("Transform", IsNullable = false)]
    public TransformType[]? Transforms { get; set; }

    public required DigestMethodType DigestMethod { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public required byte[] DigestValue { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? URI { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? Type { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Transform", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class TransformType
{

    [XmlAnyElement()]
    [XmlElement("XPath", typeof(string))]
    public object[]? Items { get; set; }

    [XmlText()]
    public string[]? Text { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string Algorithm { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("DigestMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class DigestMethodType
{

    [XmlText()]
    [XmlAnyElement()]
    public System.Xml.XmlNode[]? Any { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string Algorithm { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Signature", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureType
{

    public required SignedInfoType SignedInfo { get; set; }

    public required SignatureValueType SignatureValue { get; set; }

    public KeyInfoType? KeyInfo { get; set; }

    [XmlElement("Object")]
    public ObjectType[]? Object { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SignedInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignedInfoType
{

    public required CanonicalizationMethodType CanonicalizationMethod { get; set; }

    public required SignatureMethodType SignatureMethod { get; set; }

    [XmlElement("Reference")]
    public required ReferenceType[] Reference { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("CanonicalizationMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class CanonicalizationMethodType
{

    [XmlText()]
    [XmlAnyElement()]
    public System.Xml.XmlNode[]? Any { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string Algorithm { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SignatureMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureMethodType
{

    [XmlElement(DataType = "integer")]
    public string? HMACOutputLength { get; set; }

    [XmlText()]
    [XmlAnyElement()]
    public System.Xml.XmlNode[]? Any { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string Algorithm { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SignatureValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignatureValueType
{

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }

    [XmlText(DataType = "base64Binary")]
    public required byte[] Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("KeyInfo", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class KeyInfoType
{

    [XmlAnyElement()]
    [XmlElement("KeyName", typeof(string))]
    [XmlElement("KeyValue", typeof(KeyValueType))]
    [XmlElement("MgmtData", typeof(string))]
    [XmlElement("PGPData", typeof(PGPDataType))]
    [XmlElement("RetrievalMethod", typeof(RetrievalMethodType))]
    [XmlElement("SPKIData", typeof(SPKIDataType))]
    [XmlElement("X509Data", typeof(X509DataType))]
    [XmlChoiceIdentifier("ItemsElementName")]
    public object[]? Items { get; set; }

    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public ItemsChoiceType2[]? ItemsElementName { get; set; }

    [XmlText()]
    public string[]? Text { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("KeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class KeyValueType
{

    [XmlAnyElement()]
    [XmlElement("DSAKeyValue", typeof(DSAKeyValueType))]
    [XmlElement("RSAKeyValue", typeof(RSAKeyValueType))]
    public required object Item { get; set; }

    [XmlText()]
    public string[]? Text { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("DSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class DSAKeyValueType
{

    [XmlElement(DataType = "base64Binary")]
    public byte[]? P { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public byte[]? Q { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public byte[]? G { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public required byte[] Y { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public byte[]? J { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public byte[]? Seed { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public byte[]? PgenCounter { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("RSAKeyValue", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class RSAKeyValueType
{

    [XmlElement(DataType = "base64Binary")]
    public required byte[] Modulus { get; set; }

    [XmlElement(DataType = "base64Binary")]
    public required byte[] Exponent { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("PGPData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class PGPDataType
{

    [XmlAnyElement()]
    [XmlElement("PGPKeyID", typeof(byte[]), DataType = "base64Binary")]
    [XmlElement("PGPKeyPacket", typeof(byte[]), DataType = "base64Binary")]
    [XmlChoiceIdentifier("ItemsElementName")]
    public required object[] Items { get; set; }

    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public required ItemsChoiceType1[] ItemsElementName { get; set; }
}

[Serializable()]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType1
{

    [XmlEnum("##any:")]
    Item,

    PGPKeyID,

    PGPKeyPacket,
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("RetrievalMethod", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class RetrievalMethodType
{

    [XmlArrayItem("Transform", IsNullable = false)]
    public TransformType[]? Transforms { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string URI { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? Type { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SPKIData", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SPKIDataType
{

    [XmlElement("SPKISexp", DataType = "base64Binary")]
    public required byte[][] SPKISexp { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement? Any { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("X509Data", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class X509DataType
{

    [XmlAnyElement()]
    [XmlElement("X509CRL", typeof(byte[]), DataType = "base64Binary")]
    [XmlElement("X509Certificate", typeof(byte[]), DataType = "base64Binary")]
    [XmlElement("X509IssuerSerial", typeof(X509IssuerSerialType))]
    [XmlElement("X509SKI", typeof(byte[]), DataType = "base64Binary")]
    [XmlElement("X509SubjectName", typeof(string))]
    [XmlChoiceIdentifier("ItemsElementName")]
    public object[]? Items { get; set; }

    [XmlElement("ItemsElementName")]
    [XmlIgnore()]
    public ItemsChoiceType[]? ItemsElementName { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
public partial class X509IssuerSerialType
{

    public required string X509IssuerName { get; set; }

    [XmlElement(DataType = "integer")]
    public required string X509SerialNumber { get; set; }
}

[Serializable()]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType
{

    [XmlEnum("##any:")]
    Item,

    X509CRL,

    X509Certificate,

    X509IssuerSerial,

    X509SKI,

    X509SubjectName,
}

[Serializable()]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#", IncludeInSchema = false)]
public enum ItemsChoiceType2
{

    [XmlEnum("##any:")]
    Item,

    KeyName,

    KeyValue,

    MgmtData,

    PGPData,

    RetrievalMethod,

    SPKIData,

    X509Data,
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Object", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class ObjectType
{

    [XmlText()]
    [XmlAnyElement()]
    public System.Xml.XmlNode[]? Any { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }

    [XmlAttribute()]
    public string? MimeType { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public string? Encoding { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0", IsNullable = false)]
public partial class NonRepudiationInformation
{

    [XmlElement("MessagePartNRInformation")]
    public required MessagePartNRInformation[] MessagePartNRInformation { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(AnonymousType = true, Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0")]
[XmlRoot(Namespace = "http://docs.oasis-open.org/ebxml-bp/ebbp-signals-2.0", IsNullable = false)]
public partial class AcceptanceAcknowledgement : SignalIdentificationInformation
{

    [XmlElement(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
    public SignatureType? Signature { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[XmlRoot(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Envelope
{

    public Header? Header { get; set; }

    public required Body Body { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[XmlRoot(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Header
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[XmlRoot(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
public partial class Body
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[XmlRoot(Namespace = "http://schemas.xmlsoap.org/soap/envelope/", IsNullable = false)]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class Fault
{

    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public required System.Xml.XmlQualifiedName faultcode { get; set; }

    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public required string faultstring { get; set; }

    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, DataType = "anyURI")]
    public string? faultactor { get; set; }

    [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public detail? detail { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://schemas.xmlsoap.org/soap/envelope/")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class detail
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName = "Envelope", Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("Envelope", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
public partial class Envelope05
{

    public Header05? Header { get; set; }

    public required Body05 Body { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName = "Header", Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("Header", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
public partial class Header05
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName = "Body", Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("Body", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
public partial class Body05
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName = "Fault", Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("Fault", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
public partial class Fault05
{

    public required faultcode Code { get; set; }

    [XmlArrayItem("Text", IsNullable = false)]
    public required reasontext[] Reason { get; set; }

    [XmlElement(DataType = "anyURI")]
    public string? Node { get; set; }

    [XmlElement(DataType = "anyURI")]
    public string? Role { get; set; }

    public detail05? Detail { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class faultcode
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{

    public required System.Xml.XmlQualifiedName Value { get; set; }

    public subcode? Subcode { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class subcode
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{

    public required System.Xml.XmlQualifiedName Value { get; set; }

    public subcode? Subcode { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
#pragma warning disable CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
public partial class reasontext
#pragma warning restore CS8981 // The type name only contains lower-cased ascii characters. Such names may become reserved for the language.
{

    [XmlAttribute(Form = System.Xml.Schema.XmlSchemaForm.Qualified, Namespace = "http://www.w3.org/XML/1998/namespace")]
    public required string lang { get; set; }

    [XmlText()]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(TypeName = "detail", Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class detail05
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("NotUnderstood", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class NotUnderstoodType
{

    [XmlAttribute()]
    public required System.Xml.XmlQualifiedName qname { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[XmlRoot("Upgrade", Namespace = "http://www.w3.org/2003/05/soap-envelope", IsNullable = false)]
public partial class UpgradeType
{

    [XmlElement("SupportedEnvelope")]
    public required SupportedEnvType[] SupportedEnvelope { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2003/05/soap-envelope")]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE1006:Naming Styles", Justification = "<Pending>")]
public partial class SupportedEnvType
{

    [XmlAttribute()]
    public required System.Xml.XmlQualifiedName qname { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("EndpointReference", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class EndpointReferenceType
{

    public required AttributedURIType Address { get; set; }

    public ReferenceParametersType? ReferenceParameters { get; set; }

    public MetadataType? Metadata { get; set; }

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("MessageID", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class AttributedURIType
{

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }

    [XmlText(DataType = "anyURI")]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("ReferenceParameters", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class ReferenceParametersType
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("Metadata", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class MetadataType
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Any { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("RelatesTo", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class RelatesToType
{

    public RelatesToType()
    {
        RelationshipType = "http://www.w3.org/2005/08/addressing/reply";
    }

    [XmlAttribute()]
    [System.ComponentModel.DefaultValue("http://www.w3.org/2005/08/addressing/reply")]
    public string? RelationshipType { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }

    [XmlText(DataType = "anyURI")]
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("RetryAfter", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class AttributedUnsignedLongType
{

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }

    [XmlText()]
    public ulong Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("ProblemHeaderQName", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class AttributedQNameType
{

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }

    [XmlText()]
    public required System.Xml.XmlQualifiedName Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2005/08/addressing")]
[XmlRoot("ProblemAction", Namespace = "http://www.w3.org/2005/08/addressing", IsNullable = false)]
public partial class ProblemActionType
{

    public AttributedURIType? Action { get; set; }

    [XmlElement(DataType = "anyURI")]
    public string? SoapAction { get; set; }

    [XmlAnyAttribute()]
    public System.Xml.XmlAttribute[]? AnyAttr { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Transforms", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class TransformsType
{

    [XmlElement("Transform")]
    public required TransformType[] Transform { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("Manifest", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class ManifestType
{

    [XmlElement("Reference")]
    public required ReferenceType[] Reference { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SignatureProperties", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignaturePropertiesType
{

    [XmlElement("SignatureProperty")]
    public required SignaturePropertyType[] SignatureProperty { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "http://www.w3.org/2000/09/xmldsig#")]
[XmlRoot("SignatureProperty", Namespace = "http://www.w3.org/2000/09/xmldsig#", IsNullable = false)]
public partial class SignaturePropertyType
{

    [XmlAnyElement()]
    public System.Xml.XmlElement[]? Items { get; set; }

    [XmlText()]
    public string[]? Text { get; set; }

    [XmlAttribute(DataType = "anyURI")]
    public required string Target { get; set; }

    [XmlAttribute(DataType = "ID")]
    public string? Id { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
[XmlRoot("PMode", Namespace = "urn:cef:edelivery:eu:as4:pmode", IsNullable = false)]
public partial class ProcessingMode
{

    public required string Id { get; set; }

    public required string Mep { get; set; }

    public required string MepBinding { get; set; }

    public PushConfiguration? PushConfiguration { get; set; }

    public PullConfiguration? PullConfiguration { get; set; }
    public Reliability? Reliability { get; set; }
    public ErrorHandling? ErrorHandling { get; set; }
    public ExceptionHandling? ExceptionHandling { get; set; }
    public Security? Security { get; set; }
    public bool AllowOverride { get; set; }

}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class PushConfiguration
{

    public required Protocol protocol { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Protocol
{
    public required string Url { get; set; }
    public bool UseChunking { get; set; }
    public bool UseHttpCompression { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class TlsConfiguration
{
    public bool IsEnabled { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class PullConfiguration
{
    public string? SubChannel { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Reliability
{
    public ReceptionAwareness? ReceptionAwareness { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class ReceptionAwareness
{
    public bool IsEnabled { get; set; }
    public int? RetryCount { get; set; }
    public int? RetryInterval { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class ErrorHandling
{
    public bool NotifyMessageProducer { get; set; }
    public required NotifyMethod NotifyMethod { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class ReceiptHandling
{
    public bool NotifyMessageProducer { get; set; }
    public required NotifyMethod NotifyMethod { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class ExceptionHandling
{
    public bool NotifyMessageProducer { get; set; }
    public required NotifyMethod NotifyMethod { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class NotifyMethod
{
    public required Parameter[] Parameters { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Parameter
{
    public required string Name { get; set; }
    public required string Value { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Security
{
    public Signing? Signing { get; set; }
    public Encryption? Encryption { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Signing
{
    public bool IsEnabled { get; set; }
    public required string PrivateKeyReference { get; set; }
    public required string Algorithm { get; set; }
    public string? HashFunction { get; set; }
}

[Serializable()]
[System.Diagnostics.DebuggerStepThrough()]
[System.ComponentModel.DesignerCategory("code")]
[XmlType(Namespace = "urn:cef:edelivery:eu:as4:pmode")]
public partial class Encryption
{
    public bool IsEnabled { get; set; }
    public required string PublicKeyReference { get; set; }
    public required string Algorithm { get; set; }
    public string? KeyTransport { get; set; }
}
