<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
    <DefaultItemExcludes>$(DefaultItemExcludes);ui/node_modules/**</DefaultItemExcludes>
    <OutputPath>..\..\output\</OutputPath>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>..\..\output\Eu.EDelivery.AS4.Fe.xml</DocumentationFile>
    <NETStandardInbox>false</NETStandardInbox>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>true</GenerateBindingRedirectsOutputType>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DefineConstants>TRACE</DefineConstants>
    <NoWarn>1701;1702;1705;1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <WarningsAsErrors>NU1605</WarningsAsErrors>
    <NoWarn>1701;1702; 1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="StartupOld.cs" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="ui\tsconfig.json" />
    <Content Remove="ui\tsconfig.webpack.json" />
  </ItemGroup>
  <ItemGroup>
    <None Include="StartupOld.cs" />
    <None Include="ui\tsconfig.json" />
    <None Include="ui\tsconfig.webpack.json" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Eu.EDelivery.AS4\Eu.EDelivery.AS4.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers\Eu.EDelivery.AS4.Receivers.csproj" />
    <ProjectReference Include="..\Eu.EDelivery.AS4.ServiceHandler\Eu.EDelivery.AS4.ServiceHandler.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Ensure.That" Version="10.1.0" />
    <PackageReference Include="HttpMultipartParser" Version="10.0.0" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.27" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.10" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.27" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.19.0" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.3" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.1.3" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.1" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.2.1" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.inprocess.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>