<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
        <OutputPath>..\..\output</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Remove="Resources\as4-encrypted-envelope.xml" />
        <None Remove="Resources\as4-soap-pullrequest.xml" />
        <None Remove="Resources\as4-soap-signed-encrypted-message-with-extra-hashtag.xml" />
        <None Remove="Resources\as4-soap-signed-encrypted-message.xml" />
        <None Remove="Resources\as4-soap-signed-message.txt" />
        <None Remove="Resources\as4-soap-signed-pullrequest.xml" />
        <None Remove="Resources\as4-soap-untrusted-signed-message.txt" />
        <None Remove="Resources\as4-soap-user-receipt-message.xml" />
        <None Remove="Resources\as4-soap-wrong-signed-message.txt" />
        <None Remove="Resources\as4-soap-wrong-signed-pullrequest.xml" />
        <None Remove="Resources\BizTalkUserMessage.xml" />
        <None Remove="Resources\holodeck-as4message.xml" />
        <None Remove="Resources\sendingprocessingmode.xml" />
        <None Remove="Resources\submitmessage-invalid-messageproperties.xml" />
        <None Remove="Resources\submitmessage-missing-collaboration-agreement-pmodeid.xml" />
        <None Remove="Resources\submitmessage-missing-collaboration-agreement.xml" />
        <None Remove="Resources\submitmessage-missing-collaboration.xml" />
        <None Remove="Resources\submitmessage-missing-payload-location.xml" />
        <None Remove="Resources\submitmessage-missing-payload-property-name.xml" />
        <None Remove="Resources\submitmessage-missing-schema-location.xml" />
        <None Remove="Resources\submitmessage.xml" />
    </ItemGroup>

    <ItemGroup>
        <Content Include="Resources\as4-encrypted-envelope.xml" />
        <Content Include="Resources\as4-soap-pullrequest.xml" />
        <Content Include="Resources\as4-soap-signed-encrypted-message-with-extra-hashtag.xml" />
        <Content Include="Resources\as4-soap-signed-encrypted-message.xml" />
        <Content Include="Resources\as4-soap-signed-message.txt" />
        <Content Include="Resources\as4-soap-signed-pullrequest.xml" />
        <Content Include="Resources\as4-soap-untrusted-signed-message.txt" />
        <Content Include="Resources\as4-soap-user-receipt-message.xml" />
        <Content Include="Resources\as4-soap-wrong-signed-message.txt" />
        <Content Include="Resources\as4-soap-wrong-signed-pullrequest.xml" />
        <Content Include="Resources\BizTalkUserMessage.xml" />
        <Content Include="Resources\holodeck-as4message.xml" />
        <Content Include="Resources\sendingprocessingmode.xml" />
        <Content Include="Resources\submitmessage-invalid-messageproperties.xml" />
        <Content Include="Resources\submitmessage-missing-collaboration-agreement-pmodeid.xml" />
        <Content Include="Resources\submitmessage-missing-collaboration-agreement.xml" />
        <Content Include="Resources\submitmessage-missing-collaboration.xml" />
        <Content Include="Resources\submitmessage-missing-payload-location.xml" />
        <Content Include="Resources\submitmessage-missing-payload-property-name.xml" />
        <Content Include="Resources\submitmessage-missing-schema-location.xml" />
        <Content Include="Resources\submitmessage.xml" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="8.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FsCheck.Xunit.v3" Version="3.3.3" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.5.1" />
        <PackageReference Include="Moq" Version="4.20.72" />
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <!--<PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />-->
        <!--<PackageReference Include="System.Drawing.Common" Version="8.0.26" />-->
        <PackageReference Include="System.Net.Http" Version="4.3.4" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" Version="3.2.2" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Eu.EDelivery.AS4.Receivers\Eu.EDelivery.AS4.Receivers.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.ServiceHandler\Eu.EDelivery.AS4.ServiceHandler.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.Steps\Eu.EDelivery.AS4.Steps.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.TestUtils\Eu.EDelivery.AS4.TestUtils.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4.Transformers\Eu.EDelivery.AS4.Transformers.csproj" />
        <ProjectReference Include="..\Eu.EDelivery.AS4\Eu.EDelivery.AS4.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit" />
        <Using Include="FsCheck" />
        <Using Include="FsCheck.Fluent" />
        <Using Include="FsCheck.Xunit" />
        <Using Include="Eu.EDelivery.AS4.TestUtils" />
    </ItemGroup>
</Project>