<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="Strategies\Retriever\FtpPayloadRetriever.cs" />
    </ItemGroup>
    <ItemGroup>
      <None Remove="Resources\Schemas\update-schemas.options.xml" />
    </ItemGroup>
    <ItemGroup>
      <Content Include="Resources\Schemas\update-schemas.options.xml" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="Heijden.Dns.Portable" Version="2.0.19" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.1" />
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.3" />
      <PackageReference Include="Microsoft.Extensions.Primitives" Version="8.0.0" />
      <PackageReference Include="MimeKitLite" Version="4.16.0" />
      <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
      <PackageReference Include="Polly" Version="8.6.6" />
      <PackageReference Include="Scrutor" Version="7.0.0" />
      <PackageReference Include="System.Linq.Dynamic.Core" Version="1.7.2" />
      <PackageReference Include="System.Reactive" Version="6.1.0" />
      <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
      <PackageReference Include="System.Runtime.Caching" Version="8.0.1" />
      <PackageReference Include="System.Security.Cryptography.Xml" Version="8.0.3" />
    </ItemGroup>
</Project>